services:
  - type: web
    name: specbuddy-api
    env: python
    region: oregon  # Change based on your user base
    plan: free      # Use 'starter' or 'pro' for more power
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    autoDeploy: true
    branch: main
    healthCheckPath: /  # Your root route
    envVars:
      - key: GROQ_API_KEY
        sync: false  # Add securely in Render dashboard
      - key: UNSPLASH_ACCESS_KEY
        sync: false
      - key: LLAMA_MODEL_REPO
        value: meta-llama/Meta-Llama-3.3-70B-versatile
      - key: TEMPERATURE
        value: "0.5"
      - key: MAX_NEW_TOKENS
        value: "1024"
